language: ruby
rvm:
  - "2.0.0"
  - "2.1.1"
  - "2.1.2"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 'COVERAGE=true rake spec:travis'

bundler_args: --without headless debug

before_install:
  - gem install bundler
